name: FB-PlotManager
main: com.freebuildserver.plotManager.PlotManagerPlugin
version: 0.1
api-version: 1.13
depend:
- PlotSquared
commands:
  menu:
    description: Ouvre le menu des plots
    usage: /menu
  manager:
    description: Commandes admin pour FB-PlotManager
    usage: /manager